defmodule HydraX.Install do
  @moduledoc """
  Exports deployment-ready install artifacts from the current runtime state.
  """

  alias HydraX.Config
  alias HydraX.Runtime

  def export_snapshot(output_root \\ Config.install_root()) do
    File.mkdir_p!(output_root)

    snapshot = Runtime.install_snapshot()
    env_path = Path.join(output_root, ".env.preview")
    note_path = Path.join(output_root, "README-preview.md")

    File.write!(env_path, env_template(snapshot))
    File.write!(note_path, note(snapshot))

    {:ok,
     %{
       snapshot: snapshot,
       env_path: env_path,
       note_path: note_path
     }}
  end

  defp env_template(snapshot) do
    """
    # Generated by mix hydra_x.install on #{snapshot.generated_at}
    # Fill in the placeholders before using this in production.

    PHX_SERVER=true
    PHX_HOST=#{snapshot.phx_host}
    PORT=#{snapshot.port}
    DATABASE_PATH=#{snapshot.database_path}
    SECRET_KEY_BASE=CHANGE_ME_WITH_mix_phx.gen.secret
    HYDRA_X_PUBLIC_URL=#{snapshot.public_url}
    HYDRA_X_WORKSPACE_ROOT=#{snapshot.workspace_root}
    HYDRA_X_BACKUP_ROOT=#{snapshot.backup_root}
    HYDRA_X_INSTALL_ROOT=#{Config.install_root()}
    HYDRA_X_SHELL_ALLOWLIST=#{Enum.join(snapshot.shell_allowlist, ",")}
    HYDRA_X_HTTP_ALLOWLIST=#{Enum.join(snapshot.http_allowlist, ",")}
    """
  end

  defp note(snapshot) do
    items =
      Enum.map_join(snapshot.readiness.items, "\n", fn item ->
        marker = if item.status == :ok, do: "[OK]", else: "[WARN]"
        requirement = if item.required, do: "required", else: "recommended"
        "#{marker} #{item.label} (#{requirement}) - #{item.detail}"
      end)

    """
    # Hydra-X Preview Install Snapshot

    Generated at: #{snapshot.generated_at}
    Public URL: #{snapshot.public_url}
    Workspace root: #{snapshot.workspace_root}
    Backup root: #{snapshot.backup_root}
    Database path: #{snapshot.database_path}

    ## Readiness
    #{items}

    ## Next Steps
    1. Replace `SECRET_KEY_BASE`.
    2. Update `DATABASE_PATH` if the preview node should not reuse the local SQLite file.
    3. Set `HYDRA_X_PUBLIC_URL` and `PHX_HOST` to the final externally reachable host.
    4. Run `mix hydra_x.doctor` after deploying the generated env file.
    """
  end
end
