defmodule HydraX.Install do
  @moduledoc """
  Exports deployment-ready install artifacts from the current runtime state.
  """

  alias HydraX.Config
  alias HydraX.Runtime

  def export_snapshot(output_root \\ Config.install_root()) do
    File.mkdir_p!(output_root)

    snapshot = Runtime.install_snapshot()
    env_path = Path.join(output_root, ".env.preview")
    note_path = Path.join(output_root, "README-preview.md")

    File.write!(env_path, env_template(snapshot))
    File.write!(note_path, note(snapshot))

    {:ok,
     %{
       snapshot: snapshot,
       env_path: env_path,
       note_path: note_path
     }}
  end

  defp env_template(snapshot) do
    """
    # Generated by mix hydra_x.install on #{snapshot.generated_at}
    # Fill in the placeholders before using this in production.

    PHX_SERVER=true
    PHX_HOST=#{snapshot.phx_host}
    PORT=#{snapshot.port}
    HYDRA_X_REPO_ADAPTER=#{snapshot.persistence.backend}
    #{database_env_line(snapshot)}
    SECRET_KEY_BASE=CHANGE_ME_WITH_mix_phx.gen.secret
    HYDRA_X_PUBLIC_URL=#{snapshot.public_url}
    HYDRA_X_WORKSPACE_ROOT=#{snapshot.workspace_root}
    HYDRA_X_BACKUP_ROOT=#{snapshot.backup_root}
    HYDRA_X_INSTALL_ROOT=#{Config.install_root()}
    HYDRA_X_SHELL_ALLOWLIST=#{Enum.join(snapshot.shell_allowlist, ",")}
    HYDRA_X_HTTP_ALLOWLIST=#{Enum.join(snapshot.http_allowlist, ",")}
    """
  end

  defp note(snapshot) do
    items =
      Enum.map_join(snapshot.readiness.items, "\n", fn item ->
        marker = if item.status == :ok, do: "[OK]", else: "[WARN]"
        requirement = if item.required, do: "required", else: "recommended"
        "#{marker} #{item.label} (#{requirement}) - #{item.detail}"
      end)

    next_steps =
      case snapshot.readiness.next_steps do
        [] ->
          "1. No additional readiness actions are pending."

        steps ->
          Enum.with_index(steps, 1)
          |> Enum.map_join("\n", fn {step, index} -> "#{index}. #{step}" end)
      end

    """
    # Hydra-X Preview Install Snapshot

    Generated at: #{snapshot.generated_at}
    Public URL: #{snapshot.public_url}
    Workspace root: #{snapshot.workspace_root}
    Backup root: #{snapshot.backup_root}
    Persistence backend: #{snapshot.persistence.backend}
    Persistence target: #{snapshot.persistence.target || "not configured"}
    Backup mode: #{snapshot.persistence.backup_mode}
    Coordination mode: #{snapshot.coordination.mode}

    ## Readiness
    Summary: #{String.upcase(Atom.to_string(snapshot.readiness.summary))}
    Total items: #{snapshot.readiness.counts.total}
    Warnings: #{snapshot.readiness.counts.warn}
    Required warnings: #{snapshot.readiness.counts.required_warn}
    Recommended warnings: #{snapshot.readiness.counts.recommended_warn}

    #{items}

    ## Next Steps
    #{next_steps}

    ## Deployment Checklist
    1. Replace `SECRET_KEY_BASE`.
    2. #{database_checklist_step(snapshot)}
    3. Set `HYDRA_X_PUBLIC_URL` and `PHX_HOST` to the final externally reachable host.
    4. Run `mix hydra_x.doctor` after deploying the generated env file.
    """
  end

  defp database_env_line(%{persistence: %{backend: "postgres"}, database_url: url}) do
    "DATABASE_URL=#{url || "ecto://postgres:postgres@db.example.com/hydra_x"}"
  end

  defp database_env_line(%{database_path: path}) do
    "DATABASE_PATH=#{path}"
  end

  defp database_checklist_step(%{persistence: %{backend: "postgres"}}) do
    "Set `DATABASE_URL` to the shared PostgreSQL instance that will back the node."
  end

  defp database_checklist_step(_snapshot) do
    "Update `DATABASE_PATH` if the preview node should not reuse the local SQLite file."
  end
end
